### PR TITLE
spacing, ordering, autoprefixer

### PR DESCRIPTION
**Pull request by obecny**

### CODE REVIEW

**Comment by obecny** [comment]
@niqui we have mixed that already but this can be fixed quite easily (auto-format on intellij for example). New homepage we already have 4 spaces. So basically we have mix of 2 spaces and 4 spaces, but because we don't have yet so many styles it is worth to decide in advance. Personally I would go with 4 spaces for all things related to frontend, js es5/es6, css/scss etc. This is also because it is easier to read and we will avoid to deep hierarchy also. Anyway we can discuss it and choose whatever we feel is better for us ?

**Comment by niqui** [comment]
Not hugely fussed - just remember previous debates about the spacing and some people getting upset by the 4 spaces... I am happy to settle on either - just agree we need to decide sooner rather than later.

**Comment by surgence** [comment]
I would second the vote on `4 spaces`! That is the standard our BE linter uses, so it'll make it easier on full-stack devs to not have to change their settings switching between the two.

**Comment by surgence** [comment]
@obecny can you add the `.scss-lint.yml` file with the changes you are proposing? that way if it gets accepted the lint config will be ready to go! 

Thanks.

**Comment by niqui** [comment]
if the general vote is 4 spaces then I'm happy to (just need to go update some things but no biggie)

**Comment by 0pt1c** [comment]
I'd vote for 4 spaces as well

**Comment by rtimoshenko** [comment]
4 spaces is my preference.

**Comment by obecny** [comment]
@niqui @surgence @0pt1c @rtimoshenko
up

**Comment by surgence** [comment]
:+1: LGTM

**Comment by niqui** [comment]
LGTM

**Pull request merged**
